### ISSUE TITLE
Exception on checking a subtask in editor

### ISSUE THREAD

**Issue by picsel2** [diegogangl/gtg#13]
This is a report against the branch from https://github.com/getting-things-gnome/gtg/pull/894

## Description

Clicking the checkbox of a subtask in the editor leads the exception below.

## Error message

**Context:** Global generic exception

```python-traceback
Traceback (most recent call last):
  File "/app/lib/python3.11/site-packages/GTG/gtk/editor/taskview.py", line 403, in <lambda>
    checkbox.connect('toggled', lambda _: self.on_checkbox_toggle(tid))
                                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/lib/python3.11/site-packages/GTG/gtk/editor/taskview.py", line 390, in on_checkbox_toggle
    task.toggle_status()
    ^^^^^^^^^^^^^^^^^^
AttributeError: 'Task2' object has no attribute 'toggle_status'
```

**Software versions:**
* Getting Things GNOME! v0.6-309-g44aecba4-dirty
* CPython 3.11.4 (main, Nov 10 2011, 15:00:00) [GCC 13.1.0]
* GTK 4.13.0, GLib 2.77.1
* PyGLib 3.45.0, PyGObject 3.45.0
* Linux-6.4.7-200.fc38.x86_64-x86_64-with-glibc2.37
* Flatpak 1.15.4
* Flatpak runtime: runtime/org.gnome.Platform/x86_64/master (0f46faa98f0659bd8c6227e2b375f1c9d9ef27cdac3e9ff34e0c51a34d15c359)
* Flatpak app: org.gnome.GTGDevel (ad2634c3bab55ad8248b7828dda6250deebcb0bf6e5cf07ac89fd32259d3cda4)

**Comment by diegogangl** [comment]
Pushed a fix for this as well
