### ISSUE TITLE
Task editor is bright in dark mode

### ISSUE THREAD

**Issue by picsel2** [diegogangl/gtg#15]
## Description

The task editor is bright in dark mode:
![Bildschirmfoto vom 2023-08-09 18-10-44](https://github.com/diegogangl/gtg/assets/4233457/e4ea1a6c-284d-4dd3-b470-1aa8561acf1c)

## Info

This is a report against the branch from https://github.com/getting-things-gnome/gtg/pull/894

**Comment by diegogangl** [comment]
Really weird, I can't target the background with css at all. This might be related to the change to GtkSourceView a while ago.

**Comment by diegogangl** [comment]
Pushed a fix
