### ISSUE TITLE
Defunct fold/unfold keyboard shortcuts

### ISSUE THREAD

**Issue by picsel2** [diegogangl/gtg#16]
## Description

The shortcuts for folding and unfolding a task (Shift + Left&Right-Arrow) are not working.

## Info

This is a report against the branch from https://github.com/getting-things-gnome/gtg/pull/894

**Comment by diegogangl** [comment]
IIRC those came from the treeview widget, so we need to recreate them ourselves now

**Comment by diegogangl** [comment]
Fixed!
