### ISSUE TITLE
Searching in Actionable view crashes spectacularly

### ISSUE THREAD

**Issue by picsel2** [diegogangl/gtg#18]
## Description

Performing a search in Actionable view raises tons of exceptions:
![Bildschirmfoto vom 2023-08-09 18-41-24](https://github.com/diegogangl/gtg/assets/4233457/0a759436-b383-4103-9ff1-44104fb0329b)

## Steps to reproduce

1. Open Actionable view
2. Click on the search button
3. Enter anything in the search bar.
4. Enjoy!

Alternatively this is also triggered by selecting a saved search.

## Logs

**Context:** Global generic exception

```python-traceback
Traceback (most recent call last):
  File "/app/lib/python3.10/site-packages/GTG/core/filters.py", line 134, in do_match
    if self.expand:
AttributeError: 'SearchTaskFilter' object has no attribute 'expand'
```

**Software versions:**
* Getting Things GNOME! v0.6-311-gd1441c20
* CPython 3.10.12 (main, Nov 10 2011, 15:00:00) [GCC 12.2.0]
* GTK 4.10.4, GLib 2.76.3
* PyGLib 3.44.1, PyGObject 3.44.1
* Linux-6.4.7-200.fc38.x86_64-x86_64-with-glibc2.35
* Flatpak 1.15.4
* Flatpak runtime: runtime/org.gnome.Platform/x86_64/44 (584d7c3e03c7315975c6711d6503622c0b39c109b6faa89254a87d24cf918c6e)
* Flatpak app: org.gnome.GTGDevel (46fb12da4f23421e55d64c6949e23efa24ccc1f14197067b3e59865957806839)

## Info

This is a report against the branch from https://github.com/getting-things-gnome/gtg/pull/894

**Comment by diegogangl** [comment]
Fixed in latest commit o/
