### ISSUE TITLE
Changes in task text are not saved

### ISSUE THREAD

**Issue by SqAtx** [diegogangl/gtg#19]
1. Create task with title and text

![image](https://github.com/diegogangl/gtg/assets/4351932/c84e1cad-5c57-4d36-95ce-da957fb77f8a)

2. Close the task window
3. Open task again - text is gone

![image](https://github.com/diegogangl/gtg/assets/4351932/7aed5d59-739e-4ce1-9004-41581a5b7339)

Editing a task that already has text is also not saved.

That's on https://github.com/diegogangl/gtg/tree/all_ports, specifically on https://github.com/diegogangl/gtg/commit/36461288d803c6e0518cd74872d1981215bb1ea8

I tried to reproduce on master, but am running into segfaults there, so I can't confirm whether the regression actually happened on the megaport branch.

I'm looking into it, but I'm new to the code base so it's going to take a minute.

**Comment by diegogangl** [comment]
This was a one character typo (content not contents) in the `save()` function.
Thanks for reporting :)
